CREATE TABLE IF NOT EXISTS `logs` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,	
	`type` TINYTEXT NOT NULL,
	`message` TEXT NOT NULL,
	`details` TEXT NOT NULL DEFAULT '',
        `created` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;